# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17b6c1ba829eaca393765b28fb92eb3244803f414457364b7eb110e487e54c52361de1b7ec2fd7d759a4a9b2d61e33acb1bf285db5a53211f2a330e408a63d78

test:
  secret_key_base: f26225c96a785effb4238a82b29b9c07e00b16419b3fa45b755071f74487a4c3f561562b3e93d461ac5a92a05c5d0fa51e519dd14493b8df42a7838d56afeb81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
